class resolvconf::head (
  $ensure     = present,
  $header     = "Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)\n#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\n# This file is managed by Puppet, do not edit",
  $nameserver = [],
  $domain     = '',
  $search     = [],
  $options    = [],
) {

  $file = '/etc/resolvconf/resolv.conf.d/head'

  resolvconf::file { $file:
    ensure     => $ensure,
    header     => $header,
    nameserver => $nameserver,
    domain     => $domain,
    search     => $search,
    options    => $options,
  }

}
